paths:
  # Windows环境下的相对路径配置
  kb_dir: "./Knowledge_based"
  model_dir: "./model/bge-large-zh-v1.5"
  reranker_model_dir: "./model/bge-reranker-large/quietnight/bge-reranker-large"
  openai_api_base: "https://gateway.danaai.net:9443/chat/"
  openai_api_keys: "sk-5350ed9ef0af47e7ad8e19d7208ec6c9" # 请根据实际情况修改此API密钥

models:
  embeddings_model: "bge-large-zh-v1.5"
  reranker_model: "bge-reranker-large"
  llm_model: "deepseek-chat"

settings:
  batch_size: 1024
  device: "cuda"
  normalize_embeddings: true
  use_fp16: true